<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>_CDPModelTuning.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/CoreDuet.framework/_CDPModelTuning.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet (1)
 */

@interface _CDPModelTuning : NSObject {
    _CDPModelTuningState * _currentState;
    id /* block */  _heartBeat;
    _CDPSimpleModel * _model;
    int  _numberOfGridTests;
    id /* block */  _scorer;
    NSIndexSet * _testIndices;
}

@property (nonatomic, readonly) _CDPModelTuningState *currentState;
@property (nonatomic, copy) id /* block */ heartBeat;
@property (nonatomic, retain) _CDPSimpleModel *model;
@property (nonatomic, readonly) int numberOfGridTests;
@property (nonatomic, copy) id /* block */ scorer;
@property (nonatomic, retain) NSIndexSet *testIndices;

+ (void)_addArray:(float*)arg1 size:(unsigned long long)arg2 inArray:(float*)arg3;
+ (void)_cumulativeSumOfArray:(float*)arg1 size:(unsigned long long)arg2 reverse:(bool)arg3;
+ (void)_enumerateSubsetsOfSet:(unsigned int*)arg1 setLength:(unsigned long long)arg2 index:(unsigned long long)arg3 subset:(unsigned int*)arg4 subsetLength:(unsigned long long)arg5 index:(unsigned long long)arg6 callback:(id /* block */)arg7;
+ (void)_enumerateSubsetsOfSet:(unsigned int*)arg1 setLength:(unsigned long long)arg2 withSize:(unsigned long long)arg3 callback:(id /* block */)arg4;
+ (unsigned int*)_newSetDifference:(unsigned int*)arg1 setLength:(unsigned long long)arg2 subset:(unsigned int*)arg3 subsetLength:(unsigned long long)arg4;
+ (id /* block */)f1Score;
+ (id /* block */)f2Score;
+ (id /* block */)fScoreWithBeta:(float)arg1;

- (void).cxx_destruct;
- (float)_testModelWithThreshold:(float*)arg1;
- (id)currentState;
- (id /* block */)heartBeat;
- (id)model;
- (int)numberOfGridTests;
- (void)resumeTuningWithState:(id)arg1;
- (id /* block */)scorer;
- (void)setHeartBeat:(id /* block */)arg1;
- (void)setModel:(id)arg1;
- (void)setScorer:(id /* block */)arg1;
- (void)setTestIndices:(id)arg1;
- (id)testIndices;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
