<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PLCloudUploadChanges.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/PhotoLibraryServices.framework/PLCloudUploadChanges.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (1.0)
 */

@interface PLCloudUploadChanges : NSObject {
    NSMutableSet * _adjustedAssetUuids;
    NSMutableArray * _albumChanges;
    NSMutableArray * _albumInserts;
    NSMutableArray * _deletedRecords;
    NSMutableSet * _faceChangedAssetUuids;
    NSMutableArray * _faceCropChanges;
    NSMutableArray * _insertedAssets;
    NSMutableArray * _memoryChanges;
    NSMutableArray * _personChanges;
    NSMutableSet * _propertyChangedAssetUuids;
    NSMutableArray * _suggestionChanges;
    NSMutableArray * _updatedAssets;
    NSMutableArray * _updatedMasters;
    NSMutableSet * _updatedRelationship;
}

@property (nonatomic, retain) NSMutableSet *adjustedAssetUuids;
@property (nonatomic, retain) NSMutableArray *albumChanges;
@property (nonatomic, retain) NSMutableArray *albumInserts;
@property (nonatomic, retain) NSMutableArray *deletedRecords;
@property (nonatomic, retain) NSMutableSet *faceChangedAssetUuids;
@property (nonatomic, retain) NSMutableArray *faceCropChanges;
@property (nonatomic, retain) NSMutableArray *insertedAssets;
@property (nonatomic, retain) NSMutableArray *memoryChanges;
@property (nonatomic, retain) NSMutableArray *personChanges;
@property (nonatomic, retain) NSMutableSet *propertyChangedAssetUuids;
@property (nonatomic, retain) NSMutableArray *suggestionChanges;
@property (nonatomic, retain) NSMutableArray *updatedAssets;
@property (nonatomic, retain) NSMutableArray *updatedMasters;
@property (nonatomic, retain) NSMutableSet *updatedRelationship;

- (void).cxx_destruct;
- (id)adjustedAssetUuids;
- (id)albumChanges;
- (id)albumInserts;
- (id)deletedRecords;
- (id)faceChangedAssetUuids;
- (id)faceCropChanges;
- (id)init;
- (id)insertedAssets;
- (bool)isEmpty;
- (id)memoryChanges;
- (id)personChanges;
- (id)propertyChangedAssetUuids;
- (void)setAdjustedAssetUuids:(id)arg1;
- (void)setAlbumChanges:(id)arg1;
- (void)setAlbumInserts:(id)arg1;
- (void)setDeletedRecords:(id)arg1;
- (void)setFaceChangedAssetUuids:(id)arg1;
- (void)setFaceCropChanges:(id)arg1;
- (void)setInsertedAssets:(id)arg1;
- (void)setMemoryChanges:(id)arg1;
- (void)setPersonChanges:(id)arg1;
- (void)setPropertyChangedAssetUuids:(id)arg1;
- (void)setSuggestionChanges:(id)arg1;
- (void)setUpdatedAssets:(id)arg1;
- (void)setUpdatedMasters:(id)arg1;
- (void)setUpdatedRelationship:(id)arg1;
- (id)suggestionChanges;
- (id)summaryDescription;
- (id)updatedAssets;
- (id)updatedMasters;
- (id)updatedRelationship;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
