<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HDReadAuthorizationStatus.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/HealthDaemon.framework/HDReadAuthorizationStatus.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon (1)
 */

@interface HDReadAuthorizationStatus : NSObject {
    _HKAuthorizationRecord * _authorizationRecord;
    NSNumber * _deletedObjectBaselineAnchor;
    NSNumber * _objectLimitAnchor;
    NSString * _restrictedBundleIdentifier;
    NSSet * _restrictedSourceEntities;
}

@property (nonatomic, readonly) long long authorizationMode;
@property (nonatomic, readonly, copy) HDSQLitePredicate *authorizationPredicate;
@property (nonatomic, readonly, copy) _HKAuthorizationRecord *authorizationRecord;
@property (nonatomic, readonly) long long authorizationRequest;
@property (nonatomic, readonly) long long authorizationStatus;
@property (nonatomic, readonly) bool canRead;
@property (nonatomic, readonly, copy) NSNumber *deletedObjectBaselineAnchor;
@property (nonatomic, readonly) bool isAuthorizationDetermined;
@property (nonatomic, readonly, copy) NSNumber *objectLimitAnchor;
@property (nonatomic, readonly, copy) NSDate *objectLimitModifiedDate;
@property (nonatomic, readonly, copy) NSString *restrictedBundleIdentifier;
@property (nonatomic, readonly, copy) NSSet *restrictedSourceEntities;

+ (id)notDerminedReadAuthorizationStatus;
+ (id)unrestrictedReadAuthorizationStatus;

- (void).cxx_destruct;
- (long long)authorizationMode;
- (id)authorizationPredicate;
- (id)authorizationRecord;
- (long long)authorizationRequest;
- (long long)authorizationStatus;
- (bool)canRead;
- (id)deletedObjectBaselineAnchor;
- (id)description;
- (void)disableReading;
- (void)disableSharing;
- (id)initWithReadAuthorizationStatus:(long long)arg1 authorizationRequest:(long long)arg2 authorizationMode:(long long)arg3 restrictedBundleIdentifier:(id)arg4 restrictedSourceEntities:(id)arg5 deletedObjectBaselineAnchor:(id)arg6 objectLimitAnchor:(id)arg7 objectLimitModifiedDate:(id)arg8;
- (bool)isAuthorizationDetermined;
- (id)objectLimitAnchor;
- (id)objectLimitModifiedDate;
- (id)restrictedBundleIdentifier;
- (id)restrictedSourceEntities;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
