<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>AWDNFCTSMStartEvent.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/lib/libnfshared.dylib/AWDNFCTSMStartEvent.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /usr/lib/libnfshared.dylib
 */

@interface AWDNFCTSMStartEvent : PBCodable <NSCopying> {
    struct { 
        unsigned int timeDeltaFromReference : 1; 
        unsigned int timestamp : 1; 
        unsigned int idxTableAvail : 1; 
        unsigned int persistentAvail : 1; 
        unsigned int transientDeselectAvail : 1; 
        unsigned int transientResetAvail : 1; 
    }  _has;
    unsigned int  _idxTableAvail;
    unsigned int  _persistentAvail;
    unsigned long long  _timeDeltaFromReference;
    unsigned long long  _timestamp;
    unsigned int  _transientDeselectAvail;
    unsigned int  _transientResetAvail;
    NSString * _url;
    NSData * _uuidReference;
}

@property (nonatomic) bool hasIdxTableAvail;
@property (nonatomic) bool hasPersistentAvail;
@property (nonatomic) bool hasTimeDeltaFromReference;
@property (nonatomic) bool hasTimestamp;
@property (nonatomic) bool hasTransientDeselectAvail;
@property (nonatomic) bool hasTransientResetAvail;
@property (nonatomic, readonly) bool hasUrl;
@property (nonatomic, readonly) bool hasUuidReference;
@property (nonatomic) unsigned int idxTableAvail;
@property (nonatomic) unsigned int persistentAvail;
@property (nonatomic) unsigned long long timeDeltaFromReference;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) unsigned int transientDeselectAvail;
@property (nonatomic) unsigned int transientResetAvail;
@property (nonatomic, retain) NSString *url;
@property (nonatomic, retain) NSData *uuidReference;

- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasIdxTableAvail;
- (bool)hasPersistentAvail;
- (bool)hasTimeDeltaFromReference;
- (bool)hasTimestamp;
- (bool)hasTransientDeselectAvail;
- (bool)hasTransientResetAvail;
- (bool)hasUrl;
- (bool)hasUuidReference;
- (unsigned long long)hash;
- (unsigned int)idxTableAvail;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (unsigned int)persistentAvail;
- (bool)readFrom:(id)arg1;
- (void)setHasIdxTableAvail:(bool)arg1;
- (void)setHasPersistentAvail:(bool)arg1;
- (void)setHasTimeDeltaFromReference:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setHasTransientDeselectAvail:(bool)arg1;
- (void)setHasTransientResetAvail:(bool)arg1;
- (void)setIdxTableAvail:(unsigned int)arg1;
- (void)setPersistentAvail:(unsigned int)arg1;
- (void)setTimeDeltaFromReference:(unsigned long long)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (void)setTransientDeselectAvail:(unsigned int)arg1;
- (void)setTransientResetAvail:(unsigned int)arg1;
- (void)setUrl:(id)arg1;
- (void)setUuidReference:(id)arg1;
- (unsigned long long)timeDeltaFromReference;
- (unsigned long long)timestamp;
- (unsigned int)transientDeselectAvail;
- (unsigned int)transientResetAvail;
- (id)url;
- (id)uuidReference;
- (void)writeTo:(id)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
