<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ATAssetSessionTask.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/AirTrafficDevice.framework/ATAssetSessionTask.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/AirTrafficDevice.framework/AirTrafficDevice (1)
 */

@interface ATAssetSessionTask : ATSessionTask <ATAssetLinkControllerObserver> {
    ATAssetLinkController * _assetLinkController;
    bool  _cancelAtStart;
    NSMutableSet * _currentAssets;
    NSString * _dataClass;
    NSMutableSet * _failedAssets;
    unsigned long long  _failedAssetsCount;
    NSPredicate * _filterPredicate;
    NSObject<OS_dispatch_queue> * _queue;
    NSMutableOrderedSet * _remainingAssets;
    double  _retryInterval;
    NSObject<OS_dispatch_source> * _retryTimer;
    bool  _retryUntilFinished;
    id /* block */  _shouldRetryAssetBlock;
    bool  _waitingForRetry;
}

@property (nonatomic, retain) ATAssetLinkController *assetLinkController;
@property (nonatomic, readonly, copy) NSString *dataClass;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) unsigned long long failedAssetsCount;
@property (nonatomic, copy) NSPredicate *filterPredicate;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool retryUntilFinished;
@property (nonatomic, copy) id /* block */ shouldRetryAssetBlock;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_finishAsset:(id)arg1 withError:(id)arg2;
- (id)assetLinkController;
- (void)assetLinkController:(id)arg1 didFinishAsset:(id)arg2;
- (void)assetLinkController:(id)arg1 didUpdateAsset:(id)arg2;
- (void)cancel;
- (void)cancelAllAssets;
- (id)dataClass;
- (id)debugDescription;
- (unsigned long long)failedAssetsCount;
- (id)filterPredicate;
- (id)init;
- (id)initWithAssets:(id)arg1;
- (id)initWithDataClass:(id)arg1;
- (id)remainingAssets;
- (void)resume;
- (bool)retryUntilFinished;
- (id)sessionGroupingKey;
- (void)setAssetLinkController:(id)arg1;
- (void)setFilterPredicate:(id)arg1;
- (void)setRetryUntilFinished:(bool)arg1;
- (void)setShouldRetryAssetBlock:(id /* block */)arg1;
- (id /* block */)shouldRetryAssetBlock;
- (void)start;
- (void)suspend;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
