<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ATLegacyMessage.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/AirTraffic.framework/ATLegacyMessage.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/AirTraffic.framework/AirTraffic (116)
 */

@interface ATLegacyMessage : NSObject {
    NSString * _dataClass;
    unsigned int  _messageId;
    unsigned long long  _messageType;
    NSString * _name;
    NSDictionary * _params;
    NSData * _payload;
    NSError * _result;
    unsigned int  _session;
    NSData * _sig;
    double  _timestamp;
}

@property (nonatomic, retain) NSString *dataClass;
@property (nonatomic) unsigned int messageId;
@property (nonatomic) unsigned long long messageType;
@property (nonatomic, retain) NSString *name;
@property (nonatomic, retain) NSDictionary *parameters;
@property (nonatomic, retain) NSData *payload;
@property (nonatomic, retain) NSError *result;
@property (nonatomic) unsigned int sessionNumber;
@property (nonatomic, retain) NSData *sig;
@property (nonatomic) double timestamp;

// Image: /System/Library/PrivateFrameworks/AirTraffic.framework/AirTraffic

+ (id)_messageTypeString:(unsigned long long)arg1;
+ (unsigned int)currentSessionNumber;
+ (id)messageFromData:(id)arg1;
+ (id)messageFromDictionary:(id)arg1;
+ (id)messageFromHeader:(id)arg1 withParams:(id)arg2 andPayload:(id)arg3;
+ (id)messageWithName:(id)arg1 parameters:(id)arg2;
+ (id)messageWithName:(id)arg1 parameters:(id)arg2 session:(unsigned int)arg3;
+ (unsigned int)nextSessionNumber;
+ (void)setSessionNumber:(unsigned int)arg1;

- (void).cxx_destruct;
- (id)data;
- (id)dataClass;
- (id)description;
- (id)dictionary;
- (id)initWithDictionary:(id)arg1;
- (unsigned int)messageId;
- (unsigned long long)messageType;
- (id)name;
- (id)parameterForKey:(id)arg1;
- (id)parameters;
- (id)partialResponseWithParameters:(id)arg1;
- (id)payload;
- (id)responseWithResultError:(id)arg1 parameters:(id)arg2;
- (id)result;
- (unsigned int)sessionNumber;
- (void)setDataClass:(id)arg1;
- (void)setMessageId:(unsigned int)arg1;
- (void)setMessageType:(unsigned long long)arg1;
- (void)setName:(id)arg1;
- (void)setParameters:(id)arg1;
- (void)setPayload:(id)arg1;
- (void)setResult:(id)arg1;
- (void)setSessionNumber:(unsigned int)arg1;
- (void)setSig:(id)arg1;
- (void)setTimestamp:(double)arg1;
- (id)sig;
- (double)timestamp;

// Image: /System/Library/PrivateFrameworks/AirTrafficDevice.framework/AirTrafficDevice

+ (id)signedMessageWithName:(id)arg1 parameters:(id)arg2 sesssion:(unsigned int)arg3;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
