<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>NWConcrete_nw_context.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/lib/libnetwork.dylib/NWConcrete_nw_context.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /usr/lib/libnetwork.dylib
 */

@interface NWConcrete_nw_context : NSObject <OS_nw_context> {
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  activate_lock;
    unsigned int  activated;
    struct nw_hash_table { } * address_endpoints;
    struct nw_mem_buffer_manager { } * buffer_manager_128;
    struct nw_mem_buffer_manager { } * buffer_manager_16;
    struct nw_mem_buffer_manager { } * buffer_manager_2;
    struct nw_mem_buffer_manager { } * buffer_manager_64;
    struct nw_mem_buffer_manager { } * buffer_manager_8;
    void * channel_globals;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  channel_lock;
    struct nw_hash_table { } * globals;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  globals_lock;
    struct nw_hash_table { } * host_endpoints;
    char * identifier;
    unsigned int  is_implicit;
    unsigned int  isolate_protocol_cache;
    unsigned int  isolate_protocol_stack;
    struct nw_hash_table { } * other_endpoints;
    void * path_globals;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  path_lock;
    int  privacy_level;
    void * purge_timer;
    int  scheduling_mode;
    NSObject<OS_dispatch_workloop> * workloop;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)dealloc;
- (id)description;
- (id)initWithIdentifier:(const char *)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
