<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CNFRegTableLabel.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/CommunicationsSetupUI.framework/CNFRegTableLabel.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI (1)
 */

@interface CNFRegTableLabel : UIView <PSHeaderFooterView> {
    NSURL * _URLTarget;
    NSString * _URLText;
    UITableView * _cnfreg_tableView;
    bool  _isTopmostHeader;
    UILabel * _label;
    PSSpecifier * _specifier;
    CNFRegLearnMoreButton * _urlButton;
}

@property (nonatomic, copy) NSURL *URLTarget;
@property (nonatomic, copy) NSString *URLText;
@property (nonatomic) UITableView *cnfreg_tableView;
@property (nonatomic) bool isTopmostHeader;

- (void).cxx_destruct;
- (id)URLTarget;
- (id)URLText;
- (id)_URLTarget;
- (id)_URLText;
- (double)_bottomPadding;
- (double)_labelInset;
- (id)_labelText;
- (long long)_labelTextAlignment;
- (double)_topPadding;
- (void)_urlTapped:(id)arg1;
- (void)clearSpecifier;
- (id)cnfreg_tableView;
- (void)dealloc;
- (id)initWithSpecifier:(id)arg1;
- (bool)isTopmostHeader;
- (void)layoutSubviews;
- (double)preferredHeightForWidth:(double)arg1;
- (void)setCnfreg_tableView:(id)arg1;
- (void)setIsTopmostHeader:(bool)arg1;
- (void)setURLTarget:(id)arg1;
- (void)setURLText:(id)arg1;
- (void)updateLabelText;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
