<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>GEOComposedGuidanceEvent.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/GeoServices.framework/GEOComposedGuidanceEvent.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices (1364.36.4.19.8)
 */

@interface GEOComposedGuidanceEvent : NSObject {
    bool  _clampToStep;
    unsigned long long  _creationOrder;
    double  _distanceForStrings;
    double  _endValidDistance;
    unsigned long long  _enrouteNoticeIndex;
    GEOGuidanceEvent * _guidanceEvent;
    NSMutableArray * _lanes;
    GEOJunction * _maneuverJunction;
    double  _referencePointDistance;
    GEOComposedRoute * _route;
    unsigned long long  _source;
    unsigned long long  _sourceIndex;
    double  _startValidDistance;
    unsigned long long  _stepIndex;
    NSUUID * _uniqueID;
}

@property (nonatomic, readonly) NSArray *announcements;
@property (nonatomic, readonly) int composedGuidanceEventType;
@property (nonatomic, readonly) double distanceForStrings;
@property (nonatomic, readonly) int drivingSide;
@property (nonatomic, readonly) double endValidDistance;
@property (nonatomic, readonly) unsigned long long enrouteNoticeIndex;
@property (nonatomic, readonly) NSString *exclusiveSetIdentifier;
@property (nonatomic, retain) GEOGuidanceEvent *guidanceEvent;
@property (nonatomic, readonly) bool hasHaptics;
@property (nonatomic, readonly) bool hasSignGuidance;
@property (nonatomic, readonly) bool hasSpokenGuidance;
@property (nonatomic, readonly) bool isLaneGuidanceForManeuver;
@property (nonatomic, readonly) bool isSticky;
@property (nonatomic, readonly) NSArray *laneInstructions;
@property (nonatomic, readonly) NSArray *laneTitles;
@property (nonatomic, readonly) NSArray *lanes;
@property (nonatomic, readonly) int maneuverArrow;
@property (nonatomic, readonly) GEOJunction *maneuverJunction;
@property (nonatomic, readonly) unsigned long long numChainedAnnouncements;
@property (nonatomic, readonly) double referencePointDistance;
@property (nonatomic, readonly) double repetitionInterval;
@property (nonatomic, readonly) GEONameInfo *shieldInfo;
@property (nonatomic, readonly) NSArray *signDetails;
@property (nonatomic, readonly) NSArray *signTitles;
@property (nonatomic, readonly) unsigned long long source;
@property (nonatomic, readonly) unsigned long long sourceIndex;
@property (nonatomic, readonly) unsigned long long stackRanking;
@property (nonatomic, readonly) double startValidDistance;
@property (nonatomic, readonly) GEOComposedRouteStep *step;
@property (nonatomic, readonly) NSUUID *uniqueID;

- (void).cxx_destruct;
- (bool)_MapsCarPlay_isEqual:(id)arg1;
- (void)_findSource;
- (void)_lazyInit;
- (bool)_needsLazyInit;
- (id)announcements;
- (long long)compare:(id)arg1;
- (long long)compareFactoringInSpeed:(id)arg1 speed:(double)arg2;
- (long long)comparePriority:(id)arg1;
- (int)composedGuidanceEventType;
- (id)description;
- (double)desiredTimeGapToEvent:(id)arg1 chained:(bool)arg2;
- (double)distanceForStrings;
- (int)drivingSide;
- (double)endDistanceForSpeed:(double)arg1;
- (double)endValidDistance;
- (unsigned long long)enrouteNoticeIndex;
- (id)exclusiveSetIdentifier;
- (id)guidanceEvent;
- (bool)hasHaptics;
- (bool)hasSignGuidance;
- (bool)hasSpokenGuidance;
- (id)initWithGuidanceEvent:(id)arg1 stepIndex:(unsigned long long)arg2 composedRoute:(id)arg3 clampToStep:(bool)arg4;
- (bool)isLaneGuidanceForManeuver;
- (bool)isSticky;
- (bool)isValidForSpeed:(double)arg1;
- (id)laneInstructions;
- (id)laneTitles;
- (id)lanes;
- (int)maneuverArrow;
- (id)maneuverJunction;
- (unsigned long long)numChainedAnnouncements;
- (double)referencePointDistance;
- (double)repetitionInterval;
- (void)setGuidanceEvent:(id)arg1;
- (id)shieldInfo;
- (id)signDetails;
- (id)signTitles;
- (unsigned long long)source;
- (unsigned long long)sourceIndex;
- (unsigned long long)stackRanking;
- (double)startDistanceForSpeed:(double)arg1;
- (double)startValidDistance;
- (id)step;
- (double)triggerDistanceForSpeed:(double)arg1 andDuration:(id /* block */)arg2;
- (id)uniqueID;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
