<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>GEORouteIncident.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/GeoServices.framework/GEORouteIncident.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices (1364.36.4.19.8)
 */

@interface GEORouteIncident : PBCodable <NSCopying> {
    NSString * _crossStreet;
    long long  _endTime;
    bool  _endTimeReliable;
    struct { 
        unsigned int endTime : 1; 
        unsigned int startTime : 1; 
        unsigned int updateTime : 1; 
        unsigned int laneClosureCount : 1; 
        unsigned int laneClosureType : 1; 
        unsigned int significance : 1; 
        unsigned int type : 1; 
        unsigned int endTimeReliable : 1; 
    }  _has;
    NSString * _incidentId;
    NSString * _info;
    unsigned int  _laneClosureCount;
    int  _laneClosureType;
    GEOLatLng * _position;
    int  _significance;
    long long  _startTime;
    NSString * _street;
    int  _type;
    long long  _updateTime;
}

@property (nonatomic, retain) NSString *crossStreet;
@property (nonatomic) long long endTime;
@property (nonatomic) bool endTimeReliable;
@property (nonatomic, readonly) bool hasCrossStreet;
@property (nonatomic) bool hasEndTime;
@property (nonatomic) bool hasEndTimeReliable;
@property (nonatomic, readonly) bool hasIncidentId;
@property (nonatomic, readonly) bool hasInfo;
@property (nonatomic) bool hasLaneClosureCount;
@property (nonatomic) bool hasLaneClosureType;
@property (nonatomic, readonly) bool hasPosition;
@property (nonatomic) bool hasSignificance;
@property (nonatomic) bool hasStartTime;
@property (nonatomic, readonly) bool hasStreet;
@property (nonatomic) bool hasType;
@property (nonatomic) bool hasUpdateTime;
@property (nonatomic, retain) NSString *incidentId;
@property (nonatomic, retain) NSString *info;
@property (nonatomic) unsigned int laneClosureCount;
@property (nonatomic) int laneClosureType;
@property (nonatomic, retain) GEOLatLng *position;
@property (nonatomic) int significance;
@property (nonatomic) long long startTime;
@property (nonatomic, retain) NSString *street;
@property (nonatomic) int type;
@property (nonatomic) long long updateTime;

- (void).cxx_destruct;
- (int)StringAsLaneClosureType:(id)arg1;
- (int)StringAsSignificance:(id)arg1;
- (int)StringAsType:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)crossStreet;
- (id)description;
- (id)dictionaryRepresentation;
- (long long)endTime;
- (bool)endTimeReliable;
- (bool)hasCrossStreet;
- (bool)hasEndTime;
- (bool)hasEndTimeReliable;
- (bool)hasIncidentId;
- (bool)hasInfo;
- (bool)hasLaneClosureCount;
- (bool)hasLaneClosureType;
- (bool)hasPosition;
- (bool)hasSignificance;
- (bool)hasStartTime;
- (bool)hasStreet;
- (bool)hasType;
- (bool)hasUpdateTime;
- (unsigned long long)hash;
- (id)incidentId;
- (id)info;
- (bool)isEqual:(id)arg1;
- (unsigned int)laneClosureCount;
- (int)laneClosureType;
- (id)laneClosureTypeAsString:(int)arg1;
- (void)mergeFrom:(id)arg1;
- (id)position;
- (bool)readFrom:(id)arg1;
- (void)setCrossStreet:(id)arg1;
- (void)setEndTime:(long long)arg1;
- (void)setEndTimeReliable:(bool)arg1;
- (void)setHasEndTime:(bool)arg1;
- (void)setHasEndTimeReliable:(bool)arg1;
- (void)setHasLaneClosureCount:(bool)arg1;
- (void)setHasLaneClosureType:(bool)arg1;
- (void)setHasSignificance:(bool)arg1;
- (void)setHasStartTime:(bool)arg1;
- (void)setHasType:(bool)arg1;
- (void)setHasUpdateTime:(bool)arg1;
- (void)setIncidentId:(id)arg1;
- (void)setInfo:(id)arg1;
- (void)setLaneClosureCount:(unsigned int)arg1;
- (void)setLaneClosureType:(int)arg1;
- (void)setPosition:(id)arg1;
- (void)setSignificance:(int)arg1;
- (void)setStartTime:(long long)arg1;
- (void)setStreet:(id)arg1;
- (void)setType:(int)arg1;
- (void)setUpdateTime:(long long)arg1;
- (int)significance;
- (id)significanceAsString:(int)arg1;
- (long long)startTime;
- (id)street;
- (int)type;
- (id)typeAsString:(int)arg1;
- (long long)updateTime;
- (void)writeTo:(id)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
