<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>GEOTileSet.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/GeoServices.framework/GEOTileSet.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices (1364.36.4.19.8)
 */

@interface GEOTileSet : PBCodable <NSCopying> {
    NSString * _baseURL;
    int  _checksumType;
    NSMutableArray * _countryRegionWhitelists;
    unsigned int  _dataSet;
    struct { 
        unsigned int checksumType : 1; 
        unsigned int dataSet : 1; 
        unsigned int requestStyle : 1; 
        unsigned int updateBehavior : 1; 
        unsigned int multiTileURLUsesStatusCodes : 1; 
        unsigned int useAuthProxy : 1; 
    }  _has;
    NSString * _localizationURL;
    NSString * _multiTileURL;
    bool  _multiTileURLUsesStatusCodes;
    int  _requestStyle;
    int  _scale;
    int  _size;
    int  _style;
    NSMutableArray * _supportedLanguages;
    PBUnknownFields * _unknownFields;
    int  _updateBehavior;
    bool  _useAuthProxy;
    NSMutableArray * _validVersions;
}

@property (nonatomic, retain) NSString *baseURL;
@property (nonatomic) int checksumType;
@property (nonatomic, retain) NSMutableArray *countryRegionWhitelists;
@property (nonatomic) unsigned int dataSet;
@property (nonatomic, readonly) bool hasBaseURL;
@property (nonatomic) bool hasChecksumType;
@property (nonatomic) bool hasDataSet;
@property (nonatomic, readonly) bool hasLocalizationURL;
@property (nonatomic, readonly) bool hasMultiTileURL;
@property (nonatomic) bool hasMultiTileURLUsesStatusCodes;
@property (nonatomic) bool hasRequestStyle;
@property (nonatomic) bool hasUpdateBehavior;
@property (nonatomic) bool hasUseAuthProxy;
@property (nonatomic, retain) NSString *localizationURL;
@property (nonatomic, retain) NSString *multiTileURL;
@property (nonatomic) bool multiTileURLUsesStatusCodes;
@property (nonatomic) int requestStyle;
@property (nonatomic) int scale;
@property (nonatomic) int size;
@property (nonatomic) int style;
@property (nonatomic, retain) NSMutableArray *supportedLanguages;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;
@property (nonatomic) int updateBehavior;
@property (nonatomic) bool useAuthProxy;
@property (nonatomic, retain) NSMutableArray *validVersions;

+ (Class)countryRegionWhitelistType;
+ (Class)supportedLanguageType;
+ (Class)validVersionType;

- (void).cxx_destruct;
- (int)StringAsChecksumType:(id)arg1;
- (int)StringAsRequestStyle:(id)arg1;
- (int)StringAsScale:(id)arg1;
- (int)StringAsSize:(id)arg1;
- (int)StringAsStyle:(id)arg1;
- (int)StringAsUpdateBehavior:(id)arg1;
- (void)addCountryRegionWhitelist:(id)arg1;
- (void)addSupportedLanguage:(id)arg1;
- (void)addValidVersion:(id)arg1;
- (id)baseURL;
- (int)checksumType;
- (id)checksumTypeAsString:(int)arg1;
- (void)clearCountryRegionWhitelists;
- (void)clearSupportedLanguages;
- (void)clearValidVersions;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)countryRegionWhitelistAtIndex:(unsigned long long)arg1;
- (id)countryRegionWhitelists;
- (unsigned long long)countryRegionWhitelistsCount;
- (unsigned int)dataSet;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasBaseURL;
- (bool)hasChecksumType;
- (bool)hasDataSet;
- (bool)hasLocalizationURL;
- (bool)hasMultiTileURL;
- (bool)hasMultiTileURLUsesStatusCodes;
- (bool)hasRequestStyle;
- (bool)hasUpdateBehavior;
- (bool)hasUseAuthProxy;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)localizationURL;
- (void)mergeFrom:(id)arg1;
- (id)multiTileURL;
- (bool)multiTileURLUsesStatusCodes;
- (bool)readFrom:(id)arg1;
- (int)requestStyle;
- (id)requestStyleAsString:(int)arg1;
- (int)scale;
- (id)scaleAsString:(int)arg1;
- (void)setBaseURL:(id)arg1;
- (void)setChecksumType:(int)arg1;
- (void)setCountryRegionWhitelists:(id)arg1;
- (void)setDataSet:(unsigned int)arg1;
- (void)setHasChecksumType:(bool)arg1;
- (void)setHasDataSet:(bool)arg1;
- (void)setHasMultiTileURLUsesStatusCodes:(bool)arg1;
- (void)setHasRequestStyle:(bool)arg1;
- (void)setHasUpdateBehavior:(bool)arg1;
- (void)setHasUseAuthProxy:(bool)arg1;
- (void)setLocalizationURL:(id)arg1;
- (void)setMultiTileURL:(id)arg1;
- (void)setMultiTileURLUsesStatusCodes:(bool)arg1;
- (void)setRequestStyle:(int)arg1;
- (void)setScale:(int)arg1;
- (void)setSize:(int)arg1;
- (void)setStyle:(int)arg1;
- (void)setSupportedLanguages:(id)arg1;
- (void)setUpdateBehavior:(int)arg1;
- (void)setUseAuthProxy:(bool)arg1;
- (void)setValidVersions:(id)arg1;
- (int)size;
- (id)sizeAsString:(int)arg1;
- (int)style;
- (id)styleAsString:(int)arg1;
- (id)supportedLanguageAtIndex:(unsigned long long)arg1;
- (id)supportedLanguages;
- (unsigned long long)supportedLanguagesCount;
- (id)unknownFields;
- (int)updateBehavior;
- (id)updateBehaviorAsString:(int)arg1;
- (bool)useAuthProxy;
- (id)validVersionAtIndex:(unsigned long long)arg1;
- (id)validVersions;
- (unsigned long long)validVersionsCount;
- (void)writeTo:(id)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
