<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>MKTransitInfoLabelView.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/Frameworks/MapKit.framework/MKTransitInfoLabelView.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/Frameworks/MapKit.framework/MapKit (1.0)
 */

@interface MKTransitInfoLabelView : _MKUILabel {
    MKArtworkDataSourceCache * _artworkCache;
    bool  _hasCustomFont;
    bool  _hasCustomIconSize;
    bool  _hasCustomShieldSize;
    long long  _iconSize;
    NSArray * _labelItems;
    double  _maxWidth;
    long long  _shieldSize;
    double  _spaceBetweenIcons;
    double  _spaceBetweenShields;
    id /* block */  _textForTruncationGenerator;
}

@property (nonatomic, retain) MKArtworkDataSourceCache *artworkCache;
@property (nonatomic, copy) NSArray *labelItems;
@property (nonatomic) long long shieldSize;
@property (nonatomic) double spaceBetweenShields;

+ (long long)iconSizeForContentSizeCategory:(id)arg1;
+ (long long)shieldSizeForContentSizeCategory:(id)arg1;
+ (id)stringAttributesForFont:(id)arg1 lineBreakMode:(long long)arg2;

- (void).cxx_destruct;
- (void)_contentSizeCategoryDidChange;
- (id)_generateText;
- (id)_imageForArtworkDataSource:(id)arg1;
- (id)_imageForLabelItem:(id)arg1;
- (id)_imageForShieldDataSource:(id)arg1;
- (void)_setFont:(id)arg1 custom:(bool)arg2;
- (void)_setupLabelInfo;
- (id)_stringAttributes;
- (id)artworkCache;
- (void)dealloc;
- (id)init;
- (id)initWithLabelItems:(id)arg1 iconSize:(long long)arg2 shieldSize:(long long)arg3 spaceBetweenShields:(double)arg4 maxWidth:(double)arg5;
- (id)initWithMapItem:(id)arg1;
- (id)initWithMapItem:(id)arg1 maxWidth:(double)arg2;
- (id)labelItems;
- (void)setArtworkCache:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setIconSize:(long long)arg1;
- (void)setLabelItems:(id)arg1;
- (void)setMapItem:(id)arg1;
- (void)setMaxWidth:(double)arg1 textForTruncationGenerator:(id /* block */)arg2;
- (void)setShieldSize:(long long)arg1;
- (void)setSpaceBetweenIcons:(double)arg1;
- (void)setSpaceBetweenShields:(double)arg1;
- (long long)shieldSize;
- (double)spaceBetweenShields;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
