<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>STUsageReportGraphDataSet.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/ScreenTimeUI.framework/STUsageReportGraphDataSet.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI (38)
 */

@interface STUsageReportGraphDataSet : NSObject {
    NSNumber * _average;
    double  _averageAsPercentageOfMax;
    NSArray * _dataPoints;
    unsigned long long  _itemType;
    NSNumber * _max;
    unsigned long long  _timePeriod;
    NSNumber * _total;
}

@property (nonatomic, copy) NSNumber *average;
@property (nonatomic) double averageAsPercentageOfMax;
@property (nonatomic, copy) NSArray *dataPoints;
@property (nonatomic) unsigned long long itemType;
@property (nonatomic, copy) NSNumber *max;
@property (nonatomic) unsigned long long timePeriod;
@property (nonatomic, copy) NSNumber *total;

- (void).cxx_destruct;
- (id)average;
- (double)averageAsPercentageOfMax;
- (id)dataPoints;
- (id)initWithTimePeriod:(unsigned long long)arg1 itemType:(unsigned long long)arg2 total:(id)arg3 max:(id)arg4 average:(id)arg5 averageAsPercentageOfMax:(double)arg6 dataPoints:(id)arg7;
- (unsigned long long)itemType;
- (id)max;
- (void)setAverage:(id)arg1;
- (void)setAverageAsPercentageOfMax:(double)arg1;
- (void)setDataPoints:(id)arg1;
- (void)setItemType:(unsigned long long)arg1;
- (void)setMax:(id)arg1;
- (void)setTimePeriod:(unsigned long long)arg1;
- (void)setTotal:(id)arg1;
- (unsigned long long)timePeriod;
- (id)total;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
