<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TSKAccessController.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/TSReading.framework/TSKAccessController.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport (440)
 */

@interface TSKAccessController : NSObject {
    NSCondition * _cond;
    TSUWeakReference * _delegate;
    unsigned int  _outstandingTicketCount;
    NSObject<OS_dispatch_semaphore> * _outstandingTicketReadLock;
    NSMutableArray * _pendingPrimaryThreadBlocks;
    NSThread * _primaryThread;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _primaryThreadIVarLock;
    struct __CFRunLoopSource { } * _primaryThreadPingSource;
    _Atomic unsigned int  _primaryThreadQualityOfServiceClass;
    struct { 
        unsigned int useCount; 
        id ticket; 
    }  _primaryThreadTicketInfo;
    unsigned long long  _primaryThreadWriteCount;
    unsigned int  _readerCount;
    struct { 
        struct _opaque_pthread_t {} *threadId; 
        unsigned int count; 
        struct { 
            unsigned int useCount; 
            id ticket; 
        } ticketInfo; 
    }  _readerInfo;
    _Atomic struct __CFRunLoop {} * _runLoop;
    _Atomic long long  _runLoopReadCount;
    struct _opaque_pthread_rwlock_t { 
        long long __sig; 
        BOOL __opaque[192]; 
    }  _rwLock;
    bool  _secondaryThreadWriting;
    NSMutableDictionary * _signalIdentifiers;
    bool  _thenReadingOnPrimaryThread;
    NSMutableDictionary * _waitIdentifiers;
    unsigned long long  _writeBlockedPrimaryThreadCount;
    bool  _writeLockHeld;
    NSMutableArray * _writerQueue;
}

@property (readonly) bool hasRead;
@property (readonly) bool hasWrite;
@property (readonly) bool isPrimaryThread;
@property (readonly) NSThread *primaryThread;
@property (readonly) unsigned int primaryThreadQualityOfServiceClass;
@property struct __CFRunLoop { }*runLoop;

- (void)assertHasRead;
- (void)assertHasReadOrWrite;
- (void)assertHasWrite;
- (void)dealloc;
- (bool)hasRead;
- (bool)hasWrite;
- (void)i_finishReadForTicket:(id)arg1;
- (void)i_startReadForTicket:(id)arg1;
- (id)init;
- (id)initWithDelegate:(id)arg1;
- (id)initWithPrimaryRunloop:(struct __CFRunLoop { }*)arg1 delegate:(id)arg2;
- (bool)isPrimaryThread;
- (void)p_asyncPerformBlockOnPrimaryThread:(id /* block */)arg1;
- (void)p_blockPrimaryThread;
- (void)p_blockPrimaryThreadForWrite;
- (void)p_dequeueWrite;
- (void)p_didAcquireReadLock;
- (void)p_didAcquireWriteLock;
- (void)p_enqueueWriteAndBlockAllowingPendingWrites:(bool)arg1;
- (void)p_finishReadForTicketInfo:(struct { unsigned int x1; id x2; }*)arg1;
- (void)p_flushPendingPrimaryThreadBlocksQueueAcquiringLock:(bool)arg1;
- (bool)p_hasRead;
- (bool)p_hasWrite;
- (void)p_performRead:(id /* block */)arg1 eagerlyBlockingPrimaryThread:(bool)arg2 thenWrite:(id /* block */)arg3 allowingPendingWrites:(bool)arg4 thenReadOnPrimaryThread:(id /* block */)arg5;
- (void)p_performReadOnPrimaryThread:(id /* block */)arg1 result:(bool)arg2;
- (void)p_readLock;
- (void)p_readLockTakingRealLock:(bool)arg1;
- (void)p_readUnlock;
- (void)p_readUnlockReleasingRealLock:(bool)arg1;
- (void)p_releaseRunLoop:(struct __CFRunLoop { }*)arg1;
- (void)p_schedulePrimaryThreadRead:(id /* block */)arg1 result:(bool)arg2;
- (void)p_setPrimaryThreadIfNeeded;
- (void)p_signalPrimaryThreadWriteComplete;
- (void)p_signalThread:(id)arg1;
- (struct NSThread { Class x1; id x2; unsigned char x3[44]; }*)p_threadIdentifier;
- (struct { unsigned int x1; id x2; }*)p_ticketInfoForCurrentThread;
- (struct { unsigned int x1; id x2; }*)p_ticketInfoForTicket:(id)arg1;
- (void)p_unblockPrimaryThread;
- (bool)p_waitWithCondition:(id)arg1 untilDate:(id)arg2;
- (void)p_willAcquireReadLock;
- (void)p_willAcquireWriteLock;
- (void)p_willRelinquishReadLock;
- (void)p_willRelinquishWriteLock;
- (void)p_writeLockAndBlockPrimaryThread:(bool)arg1;
- (void)p_writeUnlock;
- (unsigned long long)p_writerQueueIndexOfThreadIdentifier:(struct NSThread { Class x1; id x2; unsigned char x3[44]; }*)arg1;
- (void)performRead:(id /* block */)arg1;
- (void)performRead:(id /* block */)arg1 thenWrite:(id /* block */)arg2 thenReadOnPrimaryThread:(id /* block */)arg3;
- (void)performRead:(id /* block */)arg1 thenWriteBeforePendingWrites:(id /* block */)arg2 thenReadOnPrimaryThread:(id /* block */)arg3;
- (void)performReadAllowingOverlappingImplicitRead:(id /* block */)arg1 thenWrite:(id /* block */)arg2 thenReadOnPrimaryThread:(id /* block */)arg3;
- (void)performReadGrantingTicket:(id /* block */)arg1;
- (void)performReadWithTicket:(id)arg1 block:(id /* block */)arg2;
- (void)performWrite:(id /* block */)arg1;
- (void)performWrite:(id /* block */)arg1 blockPrimaryThread:(bool)arg2;
- (id)primaryThread;
- (unsigned int)primaryThreadQualityOfServiceClass;
- (struct __CFRunLoop { }*)runLoop;
- (void)setRunLoop:(struct __CFRunLoop { }*)arg1;
- (void)signalIdentifier:(id)arg1;
- (void)waitOnIdentifier:(id)arg1;
- (bool)waitOnIdentifier:(id)arg1 untilDate:(id)arg2 releaseReadWhileWaiting:(bool)arg3;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
