<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CKDApplicationMetadata.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/CloudKitDaemon.framework/CKDApplicationMetadata.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon (736.235)
 */

@interface CKDApplicationMetadata : NSObject {
    bool  _allowCustomAccounts;
    bool  _allowsParticipantPII;
    bool  _allowsPowerNapScheduling;
    NSString * _applicationIdentifier;
    NSString * _apsEnvironmentString;
    bool  _canAccessProtectionData;
    bool  _canAccessZoneProtectionData;
    bool  _canMasquerade;
    bool  _canSetDeviceIdentifier;
    bool  _canSetEnvironment;
    bool  _canUseNonLegacyShareURL;
    NSString * _clientPrefix;
    bool  _displaysSystemAcceptPrompt;
    NSString * _entitlementSpecifiedPCSServiceName;
    bool  _hasAccessDuringBuddy;
    bool  _hasLightweightPCS;
    bool  _hasTCCAuthorization;
    long long  _isApplication;
    bool  _isCKSystemService;
    bool  _isOOPUI;
}

@property (nonatomic) bool allowCustomAccounts;
@property (nonatomic) bool allowsParticipantPII;
@property (nonatomic) bool allowsPowerNapScheduling;
@property (nonatomic, retain) NSString *applicationIdentifier;
@property (nonatomic, retain) NSString *apsEnvironmentString;
@property (nonatomic) bool canAccessProtectionData;
@property (nonatomic) bool canAccessZoneProtectionData;
@property (nonatomic) bool canMasquerade;
@property (nonatomic) bool canSetDeviceIdentifier;
@property (nonatomic) bool canSetEnvironment;
@property (nonatomic) bool canUseNonLegacyShareURL;
@property (nonatomic, retain) NSString *clientPrefix;
@property (nonatomic) bool displaysSystemAcceptPrompt;
@property (nonatomic, retain) NSString *entitlementSpecifiedPCSServiceName;
@property (nonatomic) bool hasAccessDuringBuddy;
@property (nonatomic) bool hasLightweightPCS;
@property (nonatomic) bool hasTCCAuthorization;
@property (nonatomic) long long isApplication;
@property (nonatomic) bool isCKSystemService;
@property (nonatomic) bool isOOPUI;

- (void).cxx_destruct;
- (bool)allowCustomAccounts;
- (bool)allowsParticipantPII;
- (bool)allowsPowerNapScheduling;
- (id)applicationIdentifier;
- (id)apsEnvironmentString;
- (bool)canAccessProtectionData;
- (bool)canAccessZoneProtectionData;
- (bool)canMasquerade;
- (bool)canSetDeviceIdentifier;
- (bool)canSetEnvironment;
- (bool)canUseNonLegacyShareURL;
- (id)clientPrefix;
- (bool)displaysSystemAcceptPrompt;
- (id)entitlementSpecifiedPCSServiceName;
- (bool)hasAccessDuringBuddy;
- (bool)hasLightweightPCS;
- (bool)hasTCCAuthorization;
- (id)init;
- (long long)isApplication;
- (bool)isCKSystemService;
- (bool)isOOPUI;
- (void)setAllowCustomAccounts:(bool)arg1;
- (void)setAllowsParticipantPII:(bool)arg1;
- (void)setAllowsPowerNapScheduling:(bool)arg1;
- (void)setApplicationIdentifier:(id)arg1;
- (void)setApsEnvironmentString:(id)arg1;
- (void)setCanAccessProtectionData:(bool)arg1;
- (void)setCanAccessZoneProtectionData:(bool)arg1;
- (void)setCanMasquerade:(bool)arg1;
- (void)setCanSetDeviceIdentifier:(bool)arg1;
- (void)setCanSetEnvironment:(bool)arg1;
- (void)setCanUseNonLegacyShareURL:(bool)arg1;
- (void)setClientPrefix:(id)arg1;
- (void)setDisplaysSystemAcceptPrompt:(bool)arg1;
- (void)setEntitlementSpecifiedPCSServiceName:(id)arg1;
- (void)setHasAccessDuringBuddy:(bool)arg1;
- (void)setHasLightweightPCS:(bool)arg1;
- (void)setHasTCCAuthorization:(bool)arg1;
- (void)setIsApplication:(long long)arg1;
- (void)setIsCKSystemService:(bool)arg1;
- (void)setIsOOPUI:(bool)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
