<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>AWDCoreRoutineMagicalMomentsExpertInstance.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/lib/libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsExpertInstance.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@interface AWDCoreRoutineMagicalMomentsExpertInstance : PBCodable <NSCopying> {
    NSMutableArray * _addons;
    int  _confidence;
    int  _expertType;
    struct { 
        unsigned int confidence : 1; 
        unsigned int expertType : 1; 
        unsigned int modelType : 1; 
        unsigned int sampleCounts : 1; 
    }  _has;
    NSMutableArray * _instances;
    int  _modelType;
    int  _sampleCounts;
}

@property (nonatomic, retain) NSMutableArray *addons;
@property (nonatomic) int confidence;
@property (nonatomic) int expertType;
@property (nonatomic) bool hasConfidence;
@property (nonatomic) bool hasExpertType;
@property (nonatomic) bool hasModelType;
@property (nonatomic) bool hasSampleCounts;
@property (nonatomic, retain) NSMutableArray *instances;
@property (nonatomic) int modelType;
@property (nonatomic) int sampleCounts;

+ (Class)addonsType;
+ (Class)instancesType;

- (void)addAddons:(id)arg1;
- (void)addInstances:(id)arg1;
- (id)addons;
- (id)addonsAtIndex:(unsigned long long)arg1;
- (unsigned long long)addonsCount;
- (void)clearAddons;
- (void)clearInstances;
- (int)confidence;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (int)expertType;
- (bool)hasConfidence;
- (bool)hasExpertType;
- (bool)hasModelType;
- (bool)hasSampleCounts;
- (unsigned long long)hash;
- (id)instances;
- (id)instancesAtIndex:(unsigned long long)arg1;
- (unsigned long long)instancesCount;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (int)modelType;
- (bool)readFrom:(id)arg1;
- (int)sampleCounts;
- (void)setAddons:(id)arg1;
- (void)setConfidence:(int)arg1;
- (void)setExpertType:(int)arg1;
- (void)setHasConfidence:(bool)arg1;
- (void)setHasExpertType:(bool)arg1;
- (void)setHasModelType:(bool)arg1;
- (void)setHasSampleCounts:(bool)arg1;
- (void)setInstances:(id)arg1;
- (void)setModelType:(int)arg1;
- (void)setSampleCounts:(int)arg1;
- (void)writeTo:(id)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
