<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>AWDWiFiOtaSystemInfo.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/lib/libAWDSupportFramework.dylib/AWDWiFiOtaSystemInfo.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@interface AWDWiFiOtaSystemInfo : PBCodable <NSCopying> {
    NSData * _beaconInfo;
    NSString * _bssid;
    struct { 
        unsigned int timestamp : 1; 
    }  _has;
    NSString * _ssid;
    unsigned long long  _timestamp;
    NSString * _wpsConfigMethods;
    NSString * _wpsDeviceNameData;
    NSString * _wpsDeviceNameElement;
    NSString * _wpsManufacturerElement;
    NSString * _wpsModelName;
    NSString * _wpsModelNumber;
    NSString * _wpsPrimaryDeviceTypeCategory;
    NSString * _wpsPrimaryDeviceTypeSubCategory;
    NSString * _wpsResponseType;
}

@property (nonatomic, retain) NSData *beaconInfo;
@property (nonatomic, retain) NSString *bssid;
@property (nonatomic, readonly) bool hasBeaconInfo;
@property (nonatomic, readonly) bool hasBssid;
@property (nonatomic, readonly) bool hasSsid;
@property (nonatomic) bool hasTimestamp;
@property (nonatomic, readonly) bool hasWpsConfigMethods;
@property (nonatomic, readonly) bool hasWpsDeviceNameData;
@property (nonatomic, readonly) bool hasWpsDeviceNameElement;
@property (nonatomic, readonly) bool hasWpsManufacturerElement;
@property (nonatomic, readonly) bool hasWpsModelName;
@property (nonatomic, readonly) bool hasWpsModelNumber;
@property (nonatomic, readonly) bool hasWpsPrimaryDeviceTypeCategory;
@property (nonatomic, readonly) bool hasWpsPrimaryDeviceTypeSubCategory;
@property (nonatomic, readonly) bool hasWpsResponseType;
@property (nonatomic, retain) NSString *ssid;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic, retain) NSString *wpsConfigMethods;
@property (nonatomic, retain) NSString *wpsDeviceNameData;
@property (nonatomic, retain) NSString *wpsDeviceNameElement;
@property (nonatomic, retain) NSString *wpsManufacturerElement;
@property (nonatomic, retain) NSString *wpsModelName;
@property (nonatomic, retain) NSString *wpsModelNumber;
@property (nonatomic, retain) NSString *wpsPrimaryDeviceTypeCategory;
@property (nonatomic, retain) NSString *wpsPrimaryDeviceTypeSubCategory;
@property (nonatomic, retain) NSString *wpsResponseType;

- (id)beaconInfo;
- (id)bssid;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasBeaconInfo;
- (bool)hasBssid;
- (bool)hasSsid;
- (bool)hasTimestamp;
- (bool)hasWpsConfigMethods;
- (bool)hasWpsDeviceNameData;
- (bool)hasWpsDeviceNameElement;
- (bool)hasWpsManufacturerElement;
- (bool)hasWpsModelName;
- (bool)hasWpsModelNumber;
- (bool)hasWpsPrimaryDeviceTypeCategory;
- (bool)hasWpsPrimaryDeviceTypeSubCategory;
- (bool)hasWpsResponseType;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setBeaconInfo:(id)arg1;
- (void)setBssid:(id)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setSsid:(id)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (void)setWpsConfigMethods:(id)arg1;
- (void)setWpsDeviceNameData:(id)arg1;
- (void)setWpsDeviceNameElement:(id)arg1;
- (void)setWpsManufacturerElement:(id)arg1;
- (void)setWpsModelName:(id)arg1;
- (void)setWpsModelNumber:(id)arg1;
- (void)setWpsPrimaryDeviceTypeCategory:(id)arg1;
- (void)setWpsPrimaryDeviceTypeSubCategory:(id)arg1;
- (void)setWpsResponseType:(id)arg1;
- (id)ssid;
- (unsigned long long)timestamp;
- (id)wpsConfigMethods;
- (id)wpsDeviceNameData;
- (id)wpsDeviceNameElement;
- (id)wpsManufacturerElement;
- (id)wpsModelName;
- (id)wpsModelNumber;
- (id)wpsPrimaryDeviceTypeCategory;
- (id)wpsPrimaryDeviceTypeSubCategory;
- (id)wpsResponseType;
- (void)writeTo:(id)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
