<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CKAttachmentItem.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/ChatKit.framework/CKAttachmentItem.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit (1.0)
 */

@interface CKAttachmentItem : NSObject <QLPreviewItem> {
    NSURL * _appendedBundleURL;
    NSDate * _createdDate;
    NSURL * _fileURL;
    NSString * _guid;
    NSString * _irisVideoPath;
    bool  _isIrisAsset;
    bool  _isSticker;
    NSURL * _previewURL;
    bool  _showDocumentIcon;
    struct CGSize { 
        double width; 
        double height; 
    }  _size;
    NSString * _transferGUID;
}

@property (nonatomic, retain) NSDate *createdDate;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSURL *fileURL;
@property (nonatomic, copy) NSString *guid;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *irisVideoPath;
@property (nonatomic) bool isIrisAsset;
@property (nonatomic) bool isSticker;
@property (nonatomic, readonly) NSString *previewItemTitle;
@property (nonatomic, readonly) NSURL *previewItemURL;
@property (nonatomic, retain) NSURL *previewURL;
@property (nonatomic) bool showDocumentIcon;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } size;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *transferGUID;

+ (id)UTITypes;
+ (struct CGSize { double x1; double x2; })defaultSize;
+ (id)previewCache;
+ (id)previewSizingQueue;
+ (unsigned long long)pxWidth;

- (void).cxx_destruct;
- (id)UTIType;
- (id)_getIrisBundleLocation;
- (id)_getIrisBundleURL;
- (void)_savePreview:(id)arg1;
- (id)_savedPreviewFromURL:(id)arg1;
- (id)cachedPreview;
- (id)calculateIrisVideoPath;
- (bool)canShareItem;
- (id)createdDate;
- (id)description;
- (id)dragItem;
- (id)fileIcon;
- (id)fileURL;
- (void)generatePreviewWithCompletion:(id /* block */)arg1;
- (id)getIrisVideoPath;
- (id)guid;
- (id)imageData;
- (id)initWithFileURL:(id)arg1 size:(struct CGSize { double x1; double x2; })arg2 transferGUID:(id)arg3 guid:(id)arg4 createdDate:(id)arg5;
- (id)irisVideoPath;
- (bool)isEqual:(id)arg1;
- (bool)isIrisAsset;
- (bool)isSticker;
- (id)pasteboardItem;
- (id)previewItemURL;
- (id)previewURL;
- (void)setCreatedDate:(id)arg1;
- (void)setFileURL:(id)arg1;
- (void)setGuid:(id)arg1;
- (void)setIrisVideoPath:(id)arg1;
- (void)setIsIrisAsset:(bool)arg1;
- (void)setIsSticker:(bool)arg1;
- (void)setPreviewURL:(id)arg1;
- (void)setShowDocumentIcon:(bool)arg1;
- (void)setTransferGUID:(id)arg1;
- (bool)showDocumentIcon;
- (struct CGSize { double x1; double x2; })size;
- (void)startDeferredSetup;
- (id)transferGUID;
- (id)uncachedPreviewURL;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
