<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CalendarEventAlarmTable.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/Frameworks/EventKitUI.framework/CalendarEventAlarmTable.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI (1.0)
 */

@interface CalendarEventAlarmTable : UITableView <UITableViewDataSource, UITableViewDelegate> {
    long long  _alarmIdentifier;
    <CalendarEventAlarmTableDelegate> * _alarmTableDelegate;
    bool  _customSelected;
    NSString * _customString;
    bool  _eventHasTravelTime;
    bool  _immediateAlarmCreation;
    bool  _leaveNowAlarmSelected;
    NSIndexPath * _selectedItem;
    bool  _shouldAllowAlarmsTriggeringAfterStartDate;
    bool  _shouldShowLeaveNowOption;
    <EKStyleProvider> * _styleProvider;
    bool  _useAllDayAlarms;
}

@property (nonatomic) <CalendarEventAlarmTableDelegate> *alarmTableDelegate;
@property (nonatomic) bool customSelected;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool eventHasTravelTime;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool leaveNowAlarmSelected;
@property (nonatomic) bool shouldAllowAlarmsTriggeringAfterStartDate;
@property (nonatomic) bool shouldShowLeaveNowOption;
@property (nonatomic, retain) <EKStyleProvider> *styleProvider;
@property (readonly) Class superclass;
@property (nonatomic) bool useAllDayAlarms;

- (void).cxx_destruct;
- (id)_indexPathForPresetIdentifier:(long long)arg1;
- (long long)_presetIdentifierForRow:(long long)arg1;
- (void)_selectIndexPath:(id)arg1;
- (id)alarmTableDelegate;
- (unsigned long long)countOfPresets;
- (bool)customSelected;
- (bool)eventHasTravelTime;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (int)intervalForPresetIdentifier:(long long)arg1;
- (bool)leaveNowAlarmSelected;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)presetIdentifier;
- (long long)presetIdentifierAtIndex:(unsigned long long)arg1;
- (void)setAlarmTableDelegate:(id)arg1;
- (void)setCustomSelected:(bool)arg1;
- (void)setCustomString:(id)arg1;
- (void)setEventHasTravelTime:(bool)arg1;
- (void)setLeaveNowAlarmSelected:(bool)arg1;
- (void)setPresetIdentifier:(long long)arg1;
- (void)setShouldAllowAlarmsTriggeringAfterStartDate:(bool)arg1;
- (void)setShouldShowLeaveNowOption:(bool)arg1;
- (void)setStyleProvider:(id)arg1;
- (void)setUseAllDayAlarms:(bool)arg1;
- (bool)shouldAllowAlarmsTriggeringAfterStartDate;
- (bool)shouldShowLeaveNowOption;
- (id)styleProvider;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayFooterView:(id)arg2 forSection:(long long)arg3;
- (bool)useAllDayAlarms;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
