<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PXPeopleBootstrapFlowController.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/PhotosUICore.framework/PXPeopleBootstrapFlowController.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore (3462.11.110)
 */

@interface PXPeopleBootstrapFlowController : NSObject <PXPeopleFlowController> {
    <PXPeopleSuggestionManagerDataSource> * _bootstrapDataSource;
    <PXPeopleBootstrapFlowDelegate> * _bootstrapDelegate;
    PXPeopleBootstrapContext * _context;
    unsigned long long  _namingResultType;
    unsigned long long  _viewControllerIndex;
    NSArray * _viewControllers;
}

@property (nonatomic, retain) <PXPeopleSuggestionManagerDataSource> *bootstrapDataSource;
@property (nonatomic, retain) <PXPeopleBootstrapFlowDelegate> *bootstrapDelegate;
@property (nonatomic, readonly) PXPeopleBootstrapContext *context;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasNextViewController;
@property (nonatomic, readonly) bool hasPreviousViewController;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long namingResultType;
@property (nonatomic, readonly) UIViewController<PXPeopleFlowViewController> *nextViewController;
@property (nonatomic, readonly) UIViewController<PXPeopleFlowViewController> *previousViewController;
@property (nonatomic, readonly) bool shouldPresentNaming;
@property (nonatomic, readonly) bool shouldPresentPostNaming;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long viewControllerIndex;
@property (nonatomic, copy) NSArray *viewControllers;

- (void).cxx_destruct;
- (id)bootstrapDataSource;
- (id)bootstrapDelegate;
- (void)cancel:(id)arg1;
- (void)commonInitWithContext:(id)arg1;
- (void)computeViewControllersForBootstrapFlow;
- (id)context;
- (void)dealloc;
- (void)done:(id)arg1;
- (bool)hasNextViewController;
- (bool)hasPreviousViewController;
- (id)init;
- (id)initEmptyFlowWithContext:(id)arg1;
- (id)initWithContext:(id)arg1;
- (unsigned long long)namingResultType;
- (id)nextViewController;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)previousViewController;
- (void)recomputeViewControllersForChangeInKeyPath:(id)arg1;
- (void)setBootstrapDataSource:(id)arg1;
- (void)setBootstrapDelegate:(id)arg1;
- (void)setNamingResultType:(unsigned long long)arg1;
- (void)setViewControllerIndex:(unsigned long long)arg1;
- (void)setViewControllers:(id)arg1;
- (bool)shouldPresentNaming;
- (bool)shouldPresentPostNaming;
- (unsigned long long)viewControllerIndex;
- (id)viewControllers;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
