<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>_UIStatistics.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/UIKitCore.framework/_UIStatistics.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore (61000)
 */

@interface _UIStatistics : NSObject {
    NSMutableSet * _children;
    NSString * _key;
    double  _sampleRate;
    double  _sampleValue;
}

@property (nonatomic) double sampleRate;

+ (id)_sharedStatisticWithDomain:(id)arg1 statisticsClass:(Class)arg2 identifierReporting:(long long)arg3;
+ (id)alertButtonTapCount;
+ (id)controlInteractionDurationDistributionWithCategory:(id)arg1 suffix:(id)arg2;
+ (id)controlTapCountWithCategory:(id)arg1 suffix:(id)arg2;
+ (id)controlValueChangeEmittedCountWithCategory:(id)arg1 suffix:(id)arg2;
+ (id)coverSheetButtonFirstActivationDurationWithCategory:(id)arg1;
+ (id)coverSheetButtonInteractionCountWithActivation:(bool)arg1 category:(id)arg2;
+ (id)coverSheetButtonInteractionDurationWithCategory:(id)arg1;
+ (id)coverSheetButtonMaximumForceWithActivation:(bool)arg1 category:(id)arg2;
+ (unsigned long long)currentTime;
+ (id)feedbackEngineActivationCountWithSuffix:(id)arg1;
+ (id)feedbackEngineActivationDurationWithSuffix:(id)arg1;
+ (id)feedbackEngineOutOfChannelsCountWithSuffix:(id)arg1;
+ (id)feedbackEnginePrewarmCountWithSuffix:(id)arg1;
+ (id)feedbackEnginePrewarmDurationWithSuffix:(id)arg1;
+ (id)feedbackGeneratorActivationCountWithSuffix:(id)arg1;
+ (id)feedbackGeneratorActivationDurationWithSuffix:(id)arg1;
+ (id)feedbackGeneratorActivationTimeOutCountWithSuffix:(id)arg1;
+ (id)feedbackGeneratorPlayCountWithSuffix:(id)arg1;
+ (id)feedbackGeneratorPreparationCountWithSuffix:(id)arg1;
+ (id)maxForce;
+ (id)pinchGestureCount;
+ (id)previewInteractionAlertPresentationCount;
+ (id)previewInteractionPeekCount;
+ (id)previewInteractionPeekDuration;
+ (id)previewInteractionPeekForce;
+ (id)previewInteractionPopCount;
+ (id)previewInteractionPopForce;
+ (id)previewInteractionTapCount;
+ (id)recentsInputViewItemSelectedCount;
+ (id)recentsInputViewNewEntryCount;
+ (id)recentsInputViewNumberOfItems;
+ (id)recentsInputViewPresentationCount;
+ (id)scrollBounceCount;
+ (id)scrollViewVerticalVelocityInteractive;
+ (id)scrollViewVerticalVelocityNoninteractive;
+ (id)scrubberUsageCount;
+ (id)scrubberUsageTime;
+ (id)zoomGestureCount;

- (void).cxx_destruct;
- (void)_addChildStatistic:(id)arg1;
- (void)_incrementValueBy:(long long)arg1;
- (id)_key;
- (void)_recordDistributionTime:(unsigned long long)arg1;
- (void)_recordDistributionValue:(double)arg1;
- (void)_removeChildStatistic:(id)arg1;
- (void)_resetDistribution;
- (void)_resetDistributionToValue:(double)arg1;
- (void)_resetValue;
- (void)_setValue:(long long)arg1;
- (bool)_shouldSample;
- (id)description;
- (id)init;
- (id)initWithDomain:(id)arg1;
- (id)initWithDomain:(id)arg1 identifierReporting:(long long)arg2;
- (void)randomizeSampleValue;
- (double)sampleRate;
- (void)setSampleRate:(double)arg1;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
