<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SFAutomaticPasswordExplanationView.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/Frameworks/SafariServices.framework/SFAutomaticPasswordExplanationView.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices (604.1)
 */

@interface SFAutomaticPasswordExplanationView : UIView <SFAutomaticPasswordScrollViewContentViewLayoutObserver, UIScrollViewDelegate, _UIScrollViewLayoutObserver> {
    UILayoutGuide * _contentLayoutGuide;
    NSLayoutConstraint * _contentLayoutGuideBottomConstraint;
    UILabel * _explanationLabel;
    NSLayoutConstraint * _iPadWidthConstraint;
    bool  _isPad;
    long long  _keyboardAppearance;
    long long  _keyboardType;
    NSLayoutConstraint * _narrowContentLeadingConstraint;
    NSLayoutConstraint * _narrowContentTrailingConstraint;
    NSArray * _narrowShadowImageViewConstraints;
    UILabel * _passwordRetrievalExpalantionLabel;
    bool  _requiresWideAppearance;
    UIScrollView * _scrollView;
    bool  _scrollViewNeedsShadowCachedValue;
    UILayoutGuide * _scrollableContentCenterLayoutGuide;
    SFAutomaticPasswordScrollViewContentView * _scrollableContentView;
    UIImageView * _shadowImageView;
    NSLayoutConstraint * _strongPasswordButtonHeightConstraint;
    NSLayoutConstraint * _strongPasswordButtonWidthConstraint;
    NSLayoutConstraint * _useCustomPasswordBaselineToBottomConstraint;
    UIButton * _useCustomPasswordButton;
    NSLayoutConstraint * _useCustomPasswordButtonWidthConstraint;
    UIButton * _useStrongPasswordButton;
    NSLayoutConstraint * _wideContentLeadingConstraint;
    double  _wideContentMaximumPadding;
    NSLayoutConstraint * _wideContentTrailingConstraint;
    NSArray * _wideShadowImageViewConstraints;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) UILabel *explanationLabel;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long keyboardAppearance;
@property (nonatomic, readonly) UILabel *passwordRetrievalExpalantionLabel;
@property (readonly) Class superclass;
@property (nonatomic, readonly) UIButton *useCustomPasswordButton;
@property (nonatomic, readonly) UIButton *useStrongPasswordButton;

- (void).cxx_destruct;
- (void)_createLayoutConstraints;
- (void)_createSubviews;
- (void)_scrollViewDidLayoutSubviews:(id)arg1;
- (bool)_scrollViewNeedsShadow:(bool)arg1;
- (void)_updateContentLayoutGuideBottomConstraint;
- (void)_updateMaximumPadding;
- (void)_updateShadowViewAlpha;
- (void)_updateStrongPasswordHeightConstraint;
- (void)_updateTextAndButtonColor;
- (void)_updateUseCustomPasswordBaselineToBottomConstraint;
- (void)_updateWideAppearanceRequirement;
- (void)automaticPasswordScrollContentViewDidLayout:(id)arg1;
- (id)explanationLabel;
- (id)initWithKeyboardType:(long long)arg1;
- (long long)keyboardAppearance;
- (void)layoutSubviews;
- (id)passwordRetrievalExpalantionLabel;
- (void)safeAreaInsetsDidChange;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setKeyboardAppearance:(long long)arg1;
- (struct CGSize { double x1; double x2; })systemLayoutSizeFittingSize:(struct CGSize { double x1; double x2; })arg1;
- (void)updateConstraints;
- (id)useCustomPasswordButton;
- (id)useStrongPasswordButton;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
