<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PSUICoreTelephonyCarrierBundleCache.h</title>
    <meta name="viewport" content="width=device-width">
    <style>
    body { margin: 1em; }
    pre { font: 11pt/1.25 ui-monospace, "SF Mono", Menlo, monospace; }
    a { color: #af52de; }
    pre { white-space: pre-wrap; }
    header, footer { color: #8e8e93; }
    header { white-space: pre; }
    footer { max-width: 700px; }
    hr { border: 0; border-top: 1px solid #c6c6c8; }
    .download { text-decoration: none; }
    @media (prefers-color-scheme: dark) {
        body { background: black; color: white; }
        a { color: #bf5af2; }
        hr { border-top-color: #333335; }
    }
    </style>
</head>
<body>
<pre><header>
 ___          _   _             ___
| _ \_  _ _ _| |_(_)_ __  ___  | _ )_ _ _____ __ _____ ___ _ _
|   / || | ' \  _| | '  \/ -_) | _ \ '_/ _ \ V  V (_-// -_) '_|
|_|_\\_,_|_||_\__|_|_|_|_\___| |___/_| \___/\_/\_//__/\___|_|


</header><hr>

/PrivateFrameworks/PreferencesUI.framework/PSUICoreTelephonyCarrierBundleCache.h <a href="?download" download title="Download" class="download">&darr;</a>


/* Generated by RuntimeBrowser
   Platform: iOS 12.5.7 (16H81) arm64
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI (1.0)
 */

@interface PSUICoreTelephonyCarrierBundleCache : NSObject <CoreTelephonyClientCarrierBundleDelegate> {
    NSMutableDictionary * _carrierBundleVersionDict;
    NSMutableDictionary * _carrierMmsInfoUrlDict;
    NSMutableDictionary * _carrierNameDict;
    NSMutableDictionary * _carrierServicesAccountUrlDict;
    NSMutableDictionary * _carrierServicesDict;
    CoreTelephonyClient * _client;
    NSMutableDictionary * _showServiceCodes;
    NSMutableDictionary * _volteCustomerCarePhoneNumberDict;
    NSMutableDictionary * _volteCustomerCareWebsiteDict;
}

@property (retain) NSMutableDictionary *carrierBundleVersionDict;
@property (retain) NSMutableDictionary *carrierMmsInfoUrlDict;
@property (retain) NSMutableDictionary *carrierNameDict;
@property (retain) NSMutableDictionary *carrierServicesAccountUrlDict;
@property (retain) NSMutableDictionary *carrierServicesDict;
@property (nonatomic, retain) CoreTelephonyClient *client;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (retain) NSMutableDictionary *showServiceCodes;
@property (readonly) Class superclass;
@property (retain) NSMutableDictionary *volteCustomerCarePhoneNumberDict;
@property (retain) NSMutableDictionary *volteCustomerCareWebsiteDict;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_clearCache;
- (id)activeDataCarrierName;
- (void)carrierBundleChange:(id)arg1;
- (id)carrierBundleValue:(id)arg1 context:(id)arg2;
- (id)carrierBundleVersion:(id)arg1;
- (id)carrierBundleVersionDict;
- (id)carrierMmsInfoUrlDict;
- (id)carrierName:(id)arg1;
- (id)carrierNameDict;
- (id)carrierServices:(id)arg1;
- (id)carrierServicesAccountTitle:(id)arg1;
- (id)carrierServicesAccountUrl:(id)arg1;
- (id)carrierServicesAccountUrlDict;
- (id)carrierServicesDict;
- (id)client;
- (id)fetchCarrierBundleValue:(id)arg1;
- (id)fetchCarrierBundleValue:(id)arg1 context:(id)arg2;
- (id)fetchCarrierBundleValueAsString:(id)arg1;
- (void)fetchCarrierBundleVersion;
- (void)fetchCarrierMmsInfoUrl;
- (void)fetchCarrierName;
- (void)fetchCarrierServices;
- (void)fetchCarrierServicesAccountUrl;
- (void)fetchShowServiceCodes;
- (void)fetchVolteCustomerCarePhoneNumber;
- (void)fetchVolteCustomerCareWebsite;
- (id)init;
- (id)initPrivate;
- (id)mmsInfoTitle:(id)arg1;
- (id)mmsInfoUrl:(id)arg1;
- (void)setCarrierBundleVersionDict:(id)arg1;
- (void)setCarrierMmsInfoUrlDict:(id)arg1;
- (void)setCarrierNameDict:(id)arg1;
- (void)setCarrierServicesAccountUrlDict:(id)arg1;
- (void)setCarrierServicesDict:(id)arg1;
- (void)setClient:(id)arg1;
- (void)setShowServiceCodes:(id)arg1;
- (void)setVolteCustomerCarePhoneNumberDict:(id)arg1;
- (void)setVolteCustomerCareWebsiteDict:(id)arg1;
- (id)showServiceCodes;
- (bool)showServiceCodes:(id)arg1;
- (id)volteCustomerCarePhoneNumber:(id)arg1;
- (id)volteCustomerCarePhoneNumberDict;
- (id)volteCustomerCareWebsite:(id)arg1;
- (id)volteCustomerCareWebsiteDict;
- (void)willEnterForeground;

@end


<hr><footer>
Source code: <a href="https://github.com/hbang/RuntimeBrowser">https://github.com/hbang/RuntimeBrowser</a>

Authors:
  Ezra Epstein (eepstein@prajna.com)
  Nicolas Seriot (nicolas@seriot.ch)
  HASHBANG Productions

Copyright &copy; 2002 by Prajna IT Consulting
Copyright &copy; 2015 by <a href="http://www.seriot.ch">Nicolas Seriot</a>
Copyright &copy; 2021 by <a href="https://hashbang.productions">HASHBANG Productions</a>

THIS PROGRAM AND THIS CODE COME WITH ABSOLUTELY NO WARRANTY. THIS CODE HAS BEEN PROVIDED "AS IS" AND THE RESPONSIBILITY FOR ITS OPERATIONS IS 100% YOURS.

RuntimeBrowser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

RuntimeBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with RuntimeBrowser (in a file called "COPYING.txt"); if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA</footer></pre>
</body>
</html>
